'GitHub Account: GitHub.com/AliRezaJoodi

Deflcdchar 1 , 16 , 16 , 16 , 16 , 16 , 16 , 16 , 16
Deflcdchar 2 , 24 , 24 , 24 , 24 , 24 , 24 , 24 , 24
Deflcdchar 3 , 28 , 28 , 28 , 28 , 28 , 28 , 28 , 28
Deflcdchar 4 , 30 , 30 , 30 , 30 , 30 , 30 , 30 , 30
Deflcdchar 5 , 31 , 31 , 31 , 31 , 31 , 31 , 31 , 31

Const Lcd_column = 16
Const Maximum_bars = Lcd_column * 5

Declare Sub Display_bar(byval percent As Byte)